[package]
name = "for-your-reference-part-1"
version = "0.1.0"
authors = ["Eric Butler <idealeric@gmail.com>", "Noah Durell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
